name: 'ðŸ”‘ Clone Private Repository'
description: 'Clone the private repository and fetch all branches and tags'

inputs:
  repository-url:
    description: 'Repository URL (owner/repo format or full URL)'
    required: true
  github-token:
    description: 'GitHub token with access to private repository'
    required: true
  target-directory:
    description: 'Target directory to clone into'
    required: false
    default: 'app'

outputs:
  repo-path:
    description: 'The repository path in owner/repo format'
    value: ${{ steps.clone.outputs.repo-path }}

runs:
  using: composite
  steps:
    - name: ðŸ“¥ Clone private repository
      id: clone
      shell: bash
      run: |
        # REPOSITORY_URL åº”è¯¥æ˜¯: owner/repo æ ¼å¼ï¼Œä¾‹å¦‚ aqz236/your-repo
        # å¦‚æžœæ˜¯å®Œæ•´URLï¼Œéœ€è¦æå– owner/repo éƒ¨åˆ†
        REPO_URL="${{ inputs.repository-url }}"
        if [[ $REPO_URL == https://github.com/* ]]; then
          # ä»Žå®Œæ•´URLä¸­æå– owner/repo
          REPO_PATH=$(echo $REPO_URL | sed 's|https://github.com/||' | sed 's|\.git$||')
        else
          # å·²ç»æ˜¯ owner/repo æ ¼å¼
          REPO_PATH=$REPO_URL
        fi

        echo "Cloning repository: $REPO_PATH"
        git clone https://${{ inputs.github-token }}@github.com/${REPO_PATH}.git ${{ inputs.target-directory }}/
        cd ${{ inputs.target-directory }}/
        git fetch --all --tags

        echo "repo-path=$REPO_PATH" >> $GITHUB_OUTPUT
        echo "Repository cloned successfully: $REPO_PATH"
