name: "ðŸ·ï¸ Generate Version"
description: "Generate version based on trigger type and repository commits"

inputs:
  app-directory:
    description: "Directory containing the private repository"
    required: false
    default: "app"

outputs:
  version:
    description: "Generated version string"
    value: ${{ steps.version.outputs.version }}
  is-prerelease:
    description: "Whether this is a prerelease"
    value: ${{ steps.version.outputs.is-prerelease }}
  private-commit:
    description: "Private repository commit hash"
    value: ${{ steps.version.outputs.private-commit }}
  private-commit-short:
    description: "Private repository short commit hash"
    value: ${{ steps.version.outputs.private-commit-short }}

runs:
  using: composite
  steps:
    - name: ðŸ·ï¸ Get version
      id: version
      shell: bash
      run: |
        # è¿›å…¥ç§æœ‰ä»“åº“ç›®å½•èŽ·å–ä¿¡æ¯
        cd ${{ inputs.app-directory }}/
        # èŽ·å–ç§æœ‰ä»“åº“çš„å½“å‰æäº¤ä¿¡æ¯
        PRIVATE_COMMIT=$(git rev-parse HEAD)
        PRIVATE_COMMIT_SHORT=$(git rev-parse --short HEAD)

        # èŽ·å–è§¦å‘æ­¤æ¬¡æž„å»ºçš„ä»“åº“ä¿¡æ¯ï¼ˆå½“å‰Actionè¿è¡Œçš„ä»“åº“ï¼‰
        TRIGGER_COMMIT="${{ github.sha }}"
        TRIGGER_COMMIT_SHORT="${TRIGGER_COMMIT:0:7}"

        # æ£€æŸ¥æ˜¯å¦æ¥è‡ª repository dispatch
        if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
          # ä½¿ç”¨è§¦å‘ä»“åº“çš„ä¿¡æ¯
          SOURCE_COMMIT="${{ github.event.client_payload.source_commit }}"
          SOURCE_COMMIT_SHORT="${SOURCE_COMMIT:0:7}"
          VERSION="v$(date +'%Y.%m.%d')-trigger-${SOURCE_COMMIT_SHORT}"
          IS_PRERELEASE=true
          echo "Triggered by repository dispatch from ${{ github.event.client_payload.source_repository }}"
          echo "Source commit: ${SOURCE_COMMIT}"
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          IS_PRERELEASE=false
        else
          # ä½¿ç”¨æ—¶é—´æˆ³ä½œä¸ºç‰ˆæœ¬å· - ç®€æ´çš„æ—¶é—´æ ¼å¼
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          VERSION="v${TIMESTAMP}"
          IS_PRERELEASE=true
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "is-prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
        echo "private-commit=$PRIVATE_COMMIT" >> $GITHUB_OUTPUT
        echo "private-commit-short=$PRIVATE_COMMIT_SHORT" >> $GITHUB_OUTPUT

        echo "Version: $VERSION"
        echo "Is prerelease: $IS_PRERELEASE"
        echo "Private repo commit: $PRIVATE_COMMIT"
        echo "Trigger repo commit: $TRIGGER_COMMIT"
