/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Github_releases_tagsIndexRouteImport } from './routes/github_releases_tags/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Github_releases_tagsIndexRoute =
  Github_releases_tagsIndexRouteImport.update({
    id: '/github_releases_tags/',
    path: '/github_releases_tags/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/github_releases_tags': typeof Github_releases_tagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/github_releases_tags': typeof Github_releases_tagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/github_releases_tags/': typeof Github_releases_tagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/github_releases_tags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/github_releases_tags'
  id: '__root__' | '/' | '/github_releases_tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Github_releases_tagsIndexRoute: typeof Github_releases_tagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github_releases_tags/': {
      id: '/github_releases_tags/'
      path: '/github_releases_tags'
      fullPath: '/github_releases_tags'
      preLoaderRoute: typeof Github_releases_tagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Github_releases_tagsIndexRoute: Github_releases_tagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
