name: "ðŸŒ Generate Release Page"
description: "Generate GitHub Pages for each release"

inputs:
  app-directory:
    description: "Directory containing the private repository"
    required: false
    default: "app"
  version:
    description: "Version string for the release"
    required: true
  commit-count:
    description: "Number of commits to show per branch"
    required: false
    default: "10"
  branches:
    description: "Comma-separated list of branches to include"
    required: false
    default: "dev,main"
  changelog:
    description: "Generated changelog content"
    required: true

outputs:
  page-url:
    description: "URL of the generated release page"
    value: ${{ steps.generate-page.outputs.page-url }}

runs:
  using: composite
  steps:
    - name: ðŸŒ Generate release page
      id: generate-page
      shell: bash
      run: |
        echo "Generating release page..."

        # è¿›å…¥ç§æœ‰ä»“åº“ç›®å½•èŽ·å–ä¿¡æ¯
        cd ${{ inputs.app-directory }}/

        # èŽ·å–å½“å‰ç§æœ‰ä»“åº“çš„ä¿¡æ¯
        CURRENT_COMMIT=$(git rev-parse HEAD)
        CURRENT_COMMIT_SHORT=$(git rev-parse --short HEAD)
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        # èŽ·å–è¿œç¨‹ä»“åº“ä¿¡æ¯
        REMOTE_URL=$(git remote get-url origin)
        if [[ $REMOTE_URL == *"github.com"* ]]; then
          REPO_PATH=$(echo $REMOTE_URL | sed 's|.*github.com[/:]\([^/]*\/[^/]*\).*|\1|' | sed 's|\.git$||')
          GITHUB_BASE_URL="https://github.com/${REPO_PATH}"
        else
          REPO_PATH=""
          GITHUB_BASE_URL=""
        fi

        # è¿”å›žæ ¹ç›®å½•
        cd ..

        # èŽ·å–è§¦å‘ä¿¡æ¯
        TRIGGER_EVENT="${{ github.event_name }}"
        TRIGGER_REPO="${{ github.repository }}"
        TRIGGER_BRANCH="${{ github.ref_name }}"
        TRIGGER_COMMIT="${{ github.sha }}"
        TRIGGER_AUTHOR="${{ github.actor }}"

        # èŽ·å–release hashä¿¡æ¯
        RELEASE_HASH="${{ github.sha }}"
        RELEASE_HASH_SHORT="${RELEASE_HASH:0:7}"

        # èŽ·å–æäº¤æ¶ˆæ¯ï¼ˆè½¬ä¹‰ç‰¹æ®Šå­—ç¬¦ï¼‰
        COMMIT_MESSAGE=""
        if [[ "${{ github.event_name }}" == "push" ]]; then
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
        elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
          COMMIT_MESSAGE="${{ github.event.client_payload.commit_message }}"
        fi
        # è½¬ä¹‰ç‰¹æ®Šå­—ç¬¦ä»¥é¿å… sed é”™è¯¯
        COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed 's/[\/&]/\\&/g' | tr '\n' ' ' | tr '\r' ' ')

        # åˆ›å»ºå‘å¸ƒç›®å½• - ä½¿ç”¨ç‰ˆæœ¬å·ï¼ˆtagåç§°ï¼‰ä½œä¸ºè·¯å¾„ï¼Œä¾¿äºŽAPIèŽ·å–
        # æ¸…ç†ç‰ˆæœ¬å·ä¸­çš„ç‰¹æ®Šå­—ç¬¦ï¼Œç”¨äºŽæ–‡ä»¶å¤¹å
        VERSION_SAFE=$(echo "${{ inputs.version }}" | sed 's/[^a-zA-Z0-9.-]/_/g')
        RELEASE_DIR="pages/${VERSION_SAFE}"
        mkdir -p "$RELEASE_DIR"

        echo "Creating release page in: $RELEASE_DIR"
        echo "Version (tag): ${{ inputs.version }}"
        echo "Version (safe): $VERSION_SAFE"
        echo "Release Hash: $RELEASE_HASH"
        echo "Release Hash (short): $RELEASE_HASH_SHORT"
        echo "Private Commit: $CURRENT_COMMIT"

        # èŽ·å–å½“å‰æ—¶é—´
        CREATED_AT=$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')        # æž„å»ºäº§ç‰©å°†é€šè¿‡å‰ç«¯JavaScriptåŠ¨æ€èŽ·å–ï¼Œç®€åŒ–åŽç«¯é€»è¾‘
        DOWNLOAD_FILES="[]"

        echo "ðŸ“ Release assets will be fetched dynamically by frontend JavaScript"
        echo "ðŸ”— GitHub API endpoints:"
        echo "  - Repository: ${{ github.repository }}"
        echo "  - Version (tag): ${{ inputs.version }}"
        echo "  - Release Hash: $RELEASE_HASH"
        echo "  - API Base: https://api.github.com/repos/${{ github.repository }}"

        # å¤åˆ¶å¹¶å¤„ç†æ¨¡æ¿æ–‡ä»¶
        cp pages/release-template.html "$RELEASE_DIR/index.html"

        # è®¾ç½®çŽ¯å¢ƒå˜é‡ä¾› Python è„šæœ¬ä½¿ç”¨
        export REPLACE_VERSION="${{ inputs.version }}"
        export REPLACE_CREATED_AT="$CREATED_AT"
        export REPLACE_COMMIT_HASH="$CURRENT_COMMIT"
        export REPLACE_PRIVATE_BRANCH="$CURRENT_BRANCH"
        export REPLACE_TRIGGER_EVENT="$TRIGGER_EVENT"
        export REPLACE_TRIGGER_REPO="$TRIGGER_REPO"
        export REPLACE_TRIGGER_BRANCH="$TRIGGER_BRANCH"
        export REPLACE_TRIGGER_COMMIT="$TRIGGER_COMMIT"
        export REPLACE_TRIGGER_AUTHOR="$TRIGGER_AUTHOR"
        export REPLACE_COMMIT_MESSAGE="$COMMIT_MESSAGE"
        export REPLACE_GITHUB_BASE_URL="$GITHUB_BASE_URL"
        export REPLACE_REPO_PATH="$REPO_PATH"
        export REPLACE_DOWNLOAD_FILES="$DOWNLOAD_FILES"
        # æ·»åŠ å‰ç«¯APIè°ƒç”¨éœ€è¦çš„å‚æ•°
        export REPLACE_RELEASE_HASH="$RELEASE_HASH"
        export REPLACE_RELEASE_HASH_SHORT="$RELEASE_HASH_SHORT"

        # å°† changelog å†™å…¥ä¸´æ—¶æ–‡ä»¶ä»¥é¿å…å¤šè¡Œå†…å®¹çš„é—®é¢˜
        CHANGELOG_FILE=$(mktemp)
        printf '%s' '${{ inputs.changelog }}' > "$CHANGELOG_FILE"
        export REPLACE_CHANGELOG_FILE="$CHANGELOG_FILE"

        # ä½¿ç”¨å¤–éƒ¨ Python è„šæœ¬å¤„ç†æ¨¡æ¿æ›¿æ¢
        python3 ./.github/actions/generate-release-page/process_template.py "$RELEASE_DIR"

        # æ¸…ç†ä¸´æ—¶æ–‡ä»¶
        rm -f "$CHANGELOG_FILE"

        # æ›´æ–° releases.json
        echo "Updating releases.json..."
        if [[ ! -f "pages/releases.json" ]]; then
          echo '{"releases":[]}' > pages/releases.json
        fi

        # å®‰è£… jq å¦‚æžœä¸å­˜åœ¨
        if ! command -v jq >/dev/null 2>&1; then
          echo "Installing jq..."
          sudo apt-get update && sudo apt-get install -y jq
        fi

        # åˆ›å»ºæ–°çš„å‘å¸ƒè®°å½•
        NEW_RELEASE=$(jq -n \
          --arg version "${{ inputs.version }}" \
          --arg commit_hash "$CURRENT_COMMIT" \
          --arg release_hash "$RELEASE_HASH" \
          --arg release_hash_short "$RELEASE_HASH_SHORT" \
          --arg created_at "$CREATED_AT" \
          --arg branch "$CURRENT_BRANCH" \
          --arg trigger_event "$TRIGGER_EVENT" \
          --arg trigger_repo "$TRIGGER_REPO" \
          --arg trigger_branch "$TRIGGER_BRANCH" \
          --arg trigger_commit "$TRIGGER_COMMIT" \
          --arg trigger_author "$TRIGGER_AUTHOR" \
          --arg commit_message "$COMMIT_MESSAGE" \
          --arg github_base_url "$GITHUB_BASE_URL" \
          --arg repo_path "$REPO_PATH" \
          --arg status "success" \
          '{
            version: $version,
            commit_hash: $commit_hash,
            release_hash: $release_hash,
            release_hash_short: $release_hash_short,
            created_at: $created_at,
            branch: $branch,
            private_branch: $branch,
            trigger_event: $trigger_event,
            trigger_repo: $trigger_repo,
            trigger_branch: $trigger_branch,
            trigger_commit: $trigger_commit,
            trigger_author: $trigger_author,
            commit_message: $commit_message,
            status: $status,
            github_base_url: $github_base_url,
            repo_path: $repo_path
          }')

        # æ£€æŸ¥æ˜¯å¦å·²å­˜åœ¨ç›¸åŒç‰ˆæœ¬çš„è®°å½•
        EXISTING=$(jq --arg version "${{ inputs.version }}" '.releases[] | select(.version == $version)' pages/releases.json)
        if [[ -z "$EXISTING" ]]; then
          # æ·»åŠ åˆ° releases.jsonï¼ˆä¿ç•™æœ€è¿‘50ä¸ªï¼‰
          jq --argjson new_release "$NEW_RELEASE" '.releases |= [($new_release)] + .[0:49]' pages/releases.json > pages/releases.json.tmp
          mv pages/releases.json.tmp pages/releases.json
          echo "Added new release: ${{ inputs.version }}"
        else
          echo "Release for version ${{ inputs.version }} already exists, updating existing record"
          # æ›´æ–°çŽ°æœ‰è®°å½•
          jq --argjson new_release "$NEW_RELEASE" '.releases = [($new_release)] + (.releases | map(select(.version != ($new_release.version))))' pages/releases.json > pages/releases.json.tmp
          mv pages/releases.json.tmp pages/releases.json
        fi

        # è¾“å‡ºé¡µé¢ URL - ä½¿ç”¨ç‰ˆæœ¬å·ï¼ˆtagåç§°ï¼‰ä½œä¸ºè·¯å¾„
        REPO_NAME=$(basename "${{ github.repository }}")
        if [[ -n "${{ github.repository }}" ]]; then
          PAGE_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/${VERSION_SAFE}/"
        else
          PAGE_URL="/${VERSION_SAFE}/"
        fi

        echo "page-url=$PAGE_URL" >> $GITHUB_OUTPUT
        echo "Generated release page: $PAGE_URL"
        echo "Files created:"
        ls -la "$RELEASE_DIR/"
        echo "Updated releases.json"
