name: "ðŸŒ Generate Release Page"
description: "Generate GitHub Pages for each release"

inputs:
  app-directory:
    description: "Directory containing the private repository"
    required: false
    default: "app"
  version:
    description: "Version string for the release"
    required: true
  commit-count:
    description: "Number of commits to show per branch"
    required: false
    default: "10"
  branches:
    description: "Comma-separated list of branches to include"
    required: false
    default: "dev,main"
  changelog:
    description: "Generated changelog content"
    required: true

outputs:
  page-url:
    description: "URL of the generated release page"
    value: ${{ steps.generate-page.outputs.page-url }}

runs:
  using: composite
  steps:
    - name: ðŸŒ Generate release page
      id: generate-page
      shell: bash
      run: |
        echo "Generating release page..."

        # è¿›å…¥ç§æœ‰ä»“åº“ç›®å½•èŽ·å–ä¿¡æ¯
        cd ${{ inputs.app-directory }}/

        # èŽ·å–å½“å‰ç§æœ‰ä»“åº“çš„ä¿¡æ¯
        CURRENT_COMMIT=$(git rev-parse HEAD)
        CURRENT_COMMIT_SHORT=$(git rev-parse --short HEAD)
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        # èŽ·å–è¿œç¨‹ä»“åº“ä¿¡æ¯
        REMOTE_URL=$(git remote get-url origin)
        if [[ $REMOTE_URL == *"github.com"* ]]; then
          REPO_PATH=$(echo $REMOTE_URL | sed 's|.*github.com[/:]\([^/]*\/[^/]*\).*|\1|' | sed 's|\.git$||')
          GITHUB_BASE_URL="https://github.com/${REPO_PATH}"
        else
          REPO_PATH=""
          GITHUB_BASE_URL=""
        fi

        # è¿”å›žæ ¹ç›®å½•
        cd ..

        # èŽ·å–è§¦å‘ä¿¡æ¯
        TRIGGER_EVENT="${{ github.event_name }}"
        TRIGGER_REPO="${{ github.repository }}"
        TRIGGER_BRANCH="${{ github.ref_name }}"
        TRIGGER_COMMIT="${{ github.sha }}"
        TRIGGER_AUTHOR="${{ github.actor }}"

        # èŽ·å–æäº¤æ¶ˆæ¯ï¼ˆè½¬ä¹‰ç‰¹æ®Šå­—ç¬¦ï¼‰
        COMMIT_MESSAGE=""
        if [[ "${{ github.event_name }}" == "push" ]]; then
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
        elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
          COMMIT_MESSAGE="${{ github.event.client_payload.commit_message }}"
        fi
        # è½¬ä¹‰ç‰¹æ®Šå­—ç¬¦ä»¥é¿å… sed é”™è¯¯
        COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed 's/[\/&]/\\&/g' | tr '\n' ' ' | tr '\r' ' ')

        # åˆ›å»ºå‘å¸ƒç›®å½•
        RELEASE_DIR="pages/${CURRENT_COMMIT}"
        mkdir -p "$RELEASE_DIR"

        echo "Creating release page in: $RELEASE_DIR"
        echo "Version: ${{ inputs.version }}"
        echo "Commit: $CURRENT_COMMIT"

        # èŽ·å–å½“å‰æ—¶é—´
        CREATED_AT=$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')

        # èŽ·å–å…³è”çš„ Release ä¸‹è½½æ–‡ä»¶ä¿¡æ¯
        DOWNLOAD_FILES="[]"

        # æŸ¥æ‰¾ä¸Žå½“å‰ç‰ˆæœ¬åŒ¹é…çš„ Release
        if [[ -n "$GITHUB_TOKEN" ]]; then
          echo "Fetching release assets for version: ${{ inputs.version }}"
          
          # å°è¯•å¤šç§ç‰ˆæœ¬æ ¼å¼
          VERSION_VARIANTS=("${{ inputs.version }}" "v${{ inputs.version }}")
          
          for VERSION_TAG in "${VERSION_VARIANTS[@]}"; do
            echo "Trying version tag: $VERSION_TAG"
            
            # ä½¿ç”¨ GitHub API èŽ·å– Release ä¿¡æ¯
            RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION_TAG" 2>/dev/null)
            
            if [[ $? -eq 0 ]] && echo "$RELEASE_INFO" | jq -e '.assets' >/dev/null 2>&1; then
              DOWNLOAD_FILES=$(echo "$RELEASE_INFO" | jq -c '.assets | map({
                name: .name,
                size: .size,
                browser_download_url: .browser_download_url,
                updated_at: .updated_at
              })')
              echo "Found $(echo "$DOWNLOAD_FILES" | jq 'length') download files for tag: $VERSION_TAG"
              break
            else
              echo "No release found for tag: $VERSION_TAG"
            fi
          done
          
          if [[ "$DOWNLOAD_FILES" == "[]" ]]; then
            echo "No assets found in any version variant, checking first release..."
            FIRST_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" 2>/dev/null)
            
            if [[ $? -eq 0 ]] && echo "$FIRST_RELEASE" | jq -e '.[0].assets' >/dev/null 2>&1; then
              FIRST_TAG=$(echo "$FIRST_RELEASE" | jq -r '.[0].tag_name')
              echo "Using assets from first release: $FIRST_TAG"
              DOWNLOAD_FILES=$(echo "$FIRST_RELEASE" | jq -c '.[0].assets | map({
                name: .name,
                size: .size,
                browser_download_url: .browser_download_url,
                updated_at: .updated_at
              })')
            fi
          fi
        else
          echo "Warning: GITHUB_TOKEN not available, cannot fetch release assets"
        fi

        # å¤åˆ¶å¹¶å¤„ç†æ¨¡æ¿æ–‡ä»¶
        cp pages/release-template.html "$RELEASE_DIR/index.html"

        # è®¾ç½®çŽ¯å¢ƒå˜é‡ä¾› Python è„šæœ¬ä½¿ç”¨
        export REPLACE_VERSION="${{ inputs.version }}"
        export REPLACE_CREATED_AT="$CREATED_AT"
        export REPLACE_COMMIT_HASH="$CURRENT_COMMIT"
        export REPLACE_PRIVATE_BRANCH="$CURRENT_BRANCH"
        export REPLACE_TRIGGER_EVENT="$TRIGGER_EVENT"
        export REPLACE_TRIGGER_REPO="$TRIGGER_REPO"
        export REPLACE_TRIGGER_BRANCH="$TRIGGER_BRANCH"
        export REPLACE_TRIGGER_COMMIT="$TRIGGER_COMMIT"
        export REPLACE_TRIGGER_AUTHOR="$TRIGGER_AUTHOR"
        export REPLACE_COMMIT_MESSAGE="$COMMIT_MESSAGE"
        export REPLACE_GITHUB_BASE_URL="$GITHUB_BASE_URL"
        export REPLACE_REPO_PATH="$REPO_PATH"
        export REPLACE_DOWNLOAD_FILES="$DOWNLOAD_FILES"

        # å°† changelog å†™å…¥ä¸´æ—¶æ–‡ä»¶ä»¥é¿å…å¤šè¡Œå†…å®¹çš„é—®é¢˜
        CHANGELOG_FILE=$(mktemp)
        printf '%s' '${{ inputs.changelog }}' > "$CHANGELOG_FILE"
        export REPLACE_CHANGELOG_FILE="$CHANGELOG_FILE"

        # ä½¿ç”¨å¤–éƒ¨ Python è„šæœ¬å¤„ç†æ¨¡æ¿æ›¿æ¢
        python3 ./.github/actions/generate-release-page/process_template.py "$RELEASE_DIR"

        # æ¸…ç†ä¸´æ—¶æ–‡ä»¶
        rm -f "$CHANGELOG_FILE"

        # æ›´æ–° releases.json
        echo "Updating releases.json..."
        if [[ ! -f "pages/releases.json" ]]; then
          echo '{"releases":[]}' > pages/releases.json
        fi

        # å®‰è£… jq å¦‚æžœä¸å­˜åœ¨
        if ! command -v jq >/dev/null 2>&1; then
          echo "Installing jq..."
          sudo apt-get update && sudo apt-get install -y jq
        fi

        # åˆ›å»ºæ–°çš„å‘å¸ƒè®°å½•
        NEW_RELEASE=$(jq -n \
          --arg version "${{ inputs.version }}" \
          --arg commit_hash "$CURRENT_COMMIT" \
          --arg created_at "$CREATED_AT" \
          --arg branch "$CURRENT_BRANCH" \
          --arg trigger_event "$TRIGGER_EVENT" \
          --arg trigger_repo "$TRIGGER_REPO" \
          --arg trigger_branch "$TRIGGER_BRANCH" \
          --arg trigger_commit "$TRIGGER_COMMIT" \
          --arg trigger_author "$TRIGGER_AUTHOR" \
          --arg commit_message "$COMMIT_MESSAGE" \
          --arg github_base_url "$GITHUB_BASE_URL" \
          --arg repo_path "$REPO_PATH" \
          --arg status "success" \
          '{
            version: $version,
            commit_hash: $commit_hash,
            created_at: $created_at,
            branch: $branch,
            private_branch: $branch,
            trigger_event: $trigger_event,
            trigger_repo: $trigger_repo,
            trigger_branch: $trigger_branch,
            trigger_commit: $trigger_commit,
            trigger_author: $trigger_author,
            commit_message: $commit_message,
            status: $status,
            github_base_url: $github_base_url,
            repo_path: $repo_path
          }')

        # æ£€æŸ¥æ˜¯å¦å·²å­˜åœ¨ç›¸åŒæäº¤çš„è®°å½•
        EXISTING=$(jq --arg commit "$CURRENT_COMMIT" '.releases[] | select(.commit_hash == $commit)' pages/releases.json)
        if [[ -z "$EXISTING" ]]; then
          # æ·»åŠ åˆ° releases.jsonï¼ˆä¿ç•™æœ€è¿‘50ä¸ªï¼‰
          jq --argjson new_release "$NEW_RELEASE" '.releases |= [($new_release)] + .[0:49]' pages/releases.json > pages/releases.json.tmp
          mv pages/releases.json.tmp pages/releases.json
          echo "Added new release: ${{ inputs.version }}"
        else
          echo "Release for commit $CURRENT_COMMIT already exists"
        fi

        # è¾“å‡ºé¡µé¢ URL
        REPO_NAME=$(basename "${{ github.repository }}")
        if [[ -n "${{ github.repository }}" ]]; then
          PAGE_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/${CURRENT_COMMIT}/"
        else
          PAGE_URL="/${CURRENT_COMMIT}/"
        fi

        echo "page-url=$PAGE_URL" >> $GITHUB_OUTPUT
        echo "Generated release page: $PAGE_URL"
        echo "Files created:"
        ls -la "$RELEASE_DIR/"
        echo "Updated releases.json"
