name: 🔨 Build Only

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      skip_release:
        description: "Skip release creation"
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: 🔨 Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: elysiajs-rapid
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact-name: linux-x64
            executable: app
          - os: macos-latest
            artifact-name: darwin-x64
            executable: app

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📥 Clone private repository
        uses: ./.github/actions/clone-private-repo
        with:
          repository-url: ${{ secrets.REPOSITORY_URL }}
          github-token: ${{ secrets.SELF_GITHUB_SECRETS }}

      - name: 🏷️ Generate version
        id: version
        uses: ./.github/actions/generate-version

      - name: 🏗️ Build application
        uses: ./.github/actions/build-app
        with:
          executable-name: ${{ matrix.executable }}
          platform: ${{ matrix.os }}

      - name: 📦 Package and encrypt
        uses: ./.github/actions/package-encrypt
        with:
          version: ${{ steps.version.outputs.version }}
          artifact-name: ${{ matrix.artifact-name }}
          encryption-password: ${{ secrets.COMPRESSED_PASSWORD }}
          platform: ${{ matrix.os }}
          executable-name: ${{ matrix.executable }}

      - name: 📤 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.artifact-name }}
          path: app-${{ steps.version.outputs.version }}-${{ matrix.artifact-name }}.7z
          retention-days: 7
